name: Build iOS App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Install the Apple certificate and provisioning profile
      run: |
        # Skip certificate installation for unsigned build
        echo "Building unsigned app - skipping certificate setup"

    - name: Cache derived data
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data-${{ hashFiles('**/*.xcodeproj', '**/*.xcworkspace') }}
        restore-keys: |
          ${{ runner.os }}-derived-data-

    - name: Build for simulator
      run: |
        xcodebuild \
          -project ApinChat.xcodeproj \
          -scheme ApinChat \
          -destination 'platform=iOS Simulator,name=iPad mini (A17 Pro),OS=latest' \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          PROVISIONING_PROFILE="" \
          clean build

    - name: Archive for device (unsigned)
      run: |
        xcodebuild \
          -project ApinChat.xcodeproj \
          -scheme ApinChat \
          -destination 'generic/platform=iOS' \
          -configuration Release \
          -archivePath $PWD/build/ApinChat.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          PROVISIONING_PROFILE="" \
          DEVELOPMENT_TEAM="" \
          archive

    - name: Export unsigned IPA
      run: |
        # Create export options plist for unsigned build
        cat > exportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>uploadBitcode</key>
            <false/>
            <key>stripSwiftSymbols</key>
            <false/>
            <key>teamID</key>
            <string></string>
        </dict>
        </plist>
        EOF

        # Export the unsigned IPA
        xcodebuild \
          -exportArchive \
          -archivePath $PWD/build/ApinChat.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath $PWD/build/export \
          -allowProvisioningUpdates

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ApinChat-Unsigned-${{ github.run_number }}
        path: |
          build/ApinChat.xcarchive
          build/export/
        retention-days: 30

    - name: Build Summary
      run: |
        echo "✅ Build completed successfully!"
        echo "📱 Unsigned iOS app built for iPad Mini A17 Pro"
        echo "📦 Artifacts uploaded with build number: ${{ github.run_number }}"
        echo "🎯 Ready for manual code signing"
        
        # Show build info
        if [ -f "build/export/ApinChat.ipa" ]; then
          echo "📄 IPA file size: $(ls -lh build/export/ApinChat.ipa | awk '{print $5}')"
        fi
